name: Pmanage test CI
on: push
jobs: 
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm i -g yarn @adonisjs/cli
      - name: Install dependencies
      - run: yarn install
      - name: Setup environment
      - run: cp .env.example .env && node ace key:generate
      - name: Run tests
      - run: yarn test
