name: Pmanage test CI
on: push
jobs: 
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        run: npm i -g yarn @adonisjs/cli && yarn
      - name: Setup environment
        run: cp .env.example .env && adonis key:generate
      - name: Run tests
        run: yarn test
